### ISSUE TITLE
free(): invalid size

### ISSUE THREAD

**Issue by jurajkapsz** [nhristov/astro-compress#316]
`v2.2.16` is causing Astro `v4.5.8` to crash, as mentioned in [this issue](https://github.com/withastro/astro/issues/9959).

Previous `v2.1.15` works fine.

**Comment by NikolaRHristov** [comment]
Maybe compressing the `_astro` directory by default in https://github.com/Playform/AstroCompress/releases/tag/v2.2.9 really wasn't such a good idea.

Removed in the latest `v2.2.17` https://github.com/Playform/AstroCompress/releases/tag/v2.2.17

Can you give it a go?

**Comment by jurajkapsz** [comment]
Yes, looking good, `v2.2.17` works like a charm. Thanks!

**Comment by zce** [comment]
> Maybe compressing the `_astro` directory by default in [`v2.2.9` (release)](https://github.com/Playform/AstroCompress/releases/tag/v2.2.9) really wasn't such a good idea.
> 
> Removed in the latest `v2.2.17` [`v2.2.17` (release)](https://github.com/Playform/AstroCompress/releases/tag/v2.2.17)
> 
> Can you give it a go?

Can you describe the specific reason for this issue?

**Comment by NikolaRHristov** [comment]
@zce I don't know. Something inside the `_astro` directory is causing issues. Maybe the image format or something else, I'll investigate further.
