### ISSUE TITLE
Dynamic import will not move module into another chunk

### ISSUE THREAD

**Issue by JuliusBairaktaris** [nhristov/astro-compress#320]
After upgrading Astro from version 2.2.15 to 2.2.20, I encountered an error when deploying my project to Cloudflare Pages. The error message indicates that there are conflicting imports of the logo.png file:

```
[plugin:vite:reporter] [plugin vite:reporter] 

logo.png is dynamically imported by /opt/buildhome/repo/src/utils/images.ts but also statically imported by /opt/buildhome/repo/src/components/Logo.astro dynamic import will not move module into another chunk.
```

This error is causing my Swiper carousels to break on the deployed site.

**Comment by NikolaRHristov** [comment]
Does it work without `CompressAstro` ?

**Comment by JuliusBairaktaris** [comment]
Yes and with compressastro 2.2.15.

**Comment by NikolaRHristov** [comment]
Can you try the latest `astro-compress` [v2.2.21](https://github.com/Playform/CompressAstro/releases/tag/AstroCompress%2Fv2.2.21) and / or `@playform/compress-astro` [v0.0.2](https://github.com/Playform/CompressAstro/releases/tag/CompressAstro%2Fv0.0.2) ? @JuliusBairaktaris

**Comment by JuliusBairaktaris** [comment]
The swiper slides work but the warning is still there. Tested with @playform/compress-astro [v0.0.2](https://github.com/Playform/CompressAstro/releases/tag/CompressAstro%2Fv0.0.2)

**Comment by NikolaRHristov** [comment]
I've cloned https://github.com/JuliusBairaktaris/astrowind locally and was able to build without `astro-compress` or `@playform/compress-astro` included and removed from `astro.config.mjs` and the `vite` warning still shows. The `vite` warning is just a warning, you can ignore it. It's not a problem with `CompressAstro`.

**Comment by JuliusBairaktaris** [comment]
Thanks for the great help!
