### ISSUE TITLE
SVG content is empty since 2.2.18

### ISSUE THREAD

**Issue by ladit** [nhristov/astro-compress#321]
[astro-compress-svg-bug.zip](https://github.com/Playform/CompressAstro/files/14812678/astro-compress-svg-bug.zip)

To reproduce it, run `npm install && astro build && astro preview`. The `dist/_astro/*.svg` will be empty. I think `compress-astro` all versions and `astro-compress >= 2.2.18` cause this problem.

My build output:

```
> astro build && astro preview

24:41:03 [build] output: "static"
24:41:03 [build] Collecting build info...
24:41:03 [build] ✓ Completed in 216ms.
24:41:03 [build] Building static entrypoints...
24:41:04 [vite] ✓ built in 581ms
24:41:04 [build] ✓ Completed in 610ms.

 generating static routes 
24:41:04 ▶ src/pages/index.astro
24:41:04   └─ /index.html (+26ms)
24:41:04 ✓ Completed in 33ms.

 generating optimized images 
24:41:04   ▶ /_astro/undraw_dog_c7i6.Br0LpN1e_2fLl9a.svg (reused cache entry) (+1ms) (1/1)
24:41:04 ✓ Completed in 2ms.


 AstroCompress processing 
(-41 Bytes)     6.71% reduction in //dist/index.html
✓ Successfully compressed a total of 1 HTML file for 41 Bytes.
(-105 Bytes)    14.02% reduction in //dist/favicon.svg
(-1.04 KB)      28.87% reduction in //dist/_astro/undraw_dog_c7i6.Br0LpN1e.svg
(-1.04 KB)      28.87% reduction in //dist/_astro/undraw_dog_c7i6.Br0LpN1e_2fLl9a.svg
✓ Successfully compressed a total of 3 SVG files for 2.18 KB.
24:41:04 [build] 1 page(s) built in 1.34s
24:41:04 [build] Complete!
```

**Comment by NikolaRHristov** [comment]
https://twitter.com/miral_kashiwagi/status/1774261574318104657?t=yPQ30a8jkLPeXNZ6gMxXFQ

**Comment by NikolaRHristov** [comment]
Could be related to the new way of saving files in `FilePipe`  [v2.1.16](https://github.com/Playform/FilePipe/compare/v2.1.15...v2.1.16) **Source/Function/Pipe.ts**

**Comment by NikolaRHristov** [comment]
Fixed in `astro-compress` [v2.2.21](https://github.com/Playform/CompressAstro/releases/tag/AstroCompress%2Fv2.2.21) and `@playform/compress-astro` [v0.0.2](https://github.com/Playform/CompressAstro/releases/tag/CompressAstro%2Fv0.0.2) ? @ladit @miralkashiwagi

**Comment by miralkashiwagi** [comment]
@NikolaRHristov 
In my project, `astro-compress` v2.2.21 worked fine. Thanks for the notification.

**Comment by ladit** [comment]
`@playform/compress-astro v0.0.2` works fine. Thank you for your work! @NikolaRHristov
