### ISSUE TITLE
Actual package name

### ISSUE THREAD

**Issue by azat-io** [nhristov/astro-compress#324]
I'm a little confused. I see three similar packages in npm:

- [astro-compress](https://www.npmjs.com/package/astro-compress)
- [compress-astro](https://www.npmjs.com/package/compress-astro)
- [@playform/compress-astro](https://www.npmjs.com/package/@playform/compress-astro)

Which of these packages should I use? What are the differences? Will the others be deprecated?
And why did the versioning start all over again?

Thank you for your hard work!

**Comment by NikolaRHristov** [comment]
They're all the same in terms of functionality and they'll all be maintained. In the future only one package will remain `@playform/compress` containing all the functionalities for compression in different frameworks `Astro`, `Next`, `Fresh`, etc.. You can use either. :) Maybe some of them will be deprecated (released to free the namespace) but I hope you'll get a notification for that as well.

**Comment by NikolaRHristov** [comment]
The versioning started from `0.0.1` as it didn't seem right to start `compress-astro` from `2.2.19`

**Comment by azat-io** [comment]
Thank you!

**Comment by NikolaRHristov** [comment]
The namespace for `compress-astro` has been freed. https://www.npmjs.com/compress-astro

**Comment by xhyrom** [comment]
Why did you change the pkg name from `@playform/compress-astro` to just `@playform/compress` ? It's chaos...

**Comment by NikolaRHristov** [comment]
> Why did you change the pkg name from `@playform/compress-astro` to just `@playform/compress` ? It's chaos...

Because in the future we will support different frameworks, `Astro`, `Next`, `Fresh`, `PHP` ones etc. and we want to have one package to rule them all not 50.
