### ISSUE TITLE
Adapt to `astro`'s `sharp` version either on `preinstall` or `postinstall`

### ISSUE THREAD

**Issue by NikolaRHristov** [nhristov/astro-compress#329]
When preinstalling make sure that the two versons of `sharp` mainly the one in `@playform/compress` and `astro` are the same. Use `@playform/adapt`

**Comment by NikolaRHristov** [comment]
And also adapt to `astro`'s current / main version.

**Comment by azat-io** [comment]
Sorry if this is a stupid question. Why don't we remove Astro from dependencies and add it to peer-dependencies with caret `^`?

**Comment by NikolaRHristov** [comment]
@azat-io We use `astro` in `devDependencies` because it's required when developing the extension. Types, etc. Having it in `peerDependencies` would mean that someone must have it installed alongside `astro-compress` or `@playform/compress` when developing the extension and that's not the case.

We use a similar pattern for `@playform/document` in https://github.com/PlayForm/Document/blob/81d9d83c72a3ad9563d7c41a15141af1f8367ea6/package.json#L51-L58 Maybe this could work.

Thanks for the suggestion ! 🎉

**Comment by NikolaRHristov** [comment]
I now see that `astro` is in `dependencies` https://github.com/PlayForm/Compress/blob/beb04ccea9634cf39b53467fe0c1309d12586b81/package.json#L45 not even in `devDependencies` since we ship the `AstroIntegration` type in https://github.com/PlayForm/Compress/blob/bec28058a7c28b8543ff3aa0a1ac8500819be3f5/Target/Interface/Integration.d.ts#L8

This https://github.com/PlayForm/Compress/blob/cce04ceb0fbb651a10d61e142e03d2c6fbfe28c1/package.json#L56-L63 should fix it.

**Comment by azat-io** [comment]
Nice. Let's do a release.

**Comment by NikolaRHristov** [comment]
@azat-io Should be fixed the latest `astro-compress` [v2.2.24](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.24) and `@playform/compress` [v0.0.6](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.6) Can you give it a go ?

**Comment by azat-io** [comment]
Yes. Thank you!
