### ISSUE TITLE
Javascript Files Getting Skipped

### ISSUE THREAD

**Issue by bcainc** [nhristov/astro-compress#341]
Why is this plugin skipping all the "hoisted.12345.js" files that Astro creates?

**Comment by NikolaRHristov** [comment]
Maybe they're already compressed at their maximum limit and couldn't be compressed more. We check for that and if the file has a larger file size after compression we don't write to it.

**Comment by NikolaRHristov** [comment]
https://github.com/PlayForm/Compress/blob/dcce142835a5b12483f79e89e9186ffeea1cdae9/Source/Variable/Option.ts#L34-L35

**Comment by bcainc** [comment]
Thank you. I think that is the case after spending more time with this ... files are silently excluded from the log output if they're already at maximum compression.
