### ISSUE TITLE
Media Queries: Range Syntax conflict

### ISSUE THREAD

**Issue by abdo-spices** [nhristov/astro-compress#367]
when file css get compressed it remove css media Query block Completely

@media screen and (width <= 868px) {
  .wtq-sidebar {
    position: absolute;
    z-index: 1;
    transform: translateX(-100%);
  }
}

to

**Comment by NikolaRHristov** [comment]
You can try disabling either `lightningcss` or `csso`:

```ts
export default (await import("astro/config")).defineConfig({
	integrations: [
		(await import("@playform/compress")).default({
			CSS: {
				// @ts-expect-error
				lightningcss: false,
				
				// or
				
				// @ts-expect-error
				csso: false,
			},
		}),
	],
}) as typeof defineConfig;

import type { defineConfig } from "astro/config";
```

**Comment by abdo-spices** [comment]
no i want css optimization

**Comment by NikolaRHristov** [comment]
Can you try disabling one of the two so we can narrow it down ? `lightningcss` was recently introduced and could be causing this.

**Comment by maple3142** [comment]
I get the same problem and solved it by disabling csso (`csso: false`).
