### ISSUE TITLE
Playform compress is breaking astro + svelte 5 production build

### ISSUE THREAD

**Issue by AdrianButler** [nhristov/astro-compress#396]
When adding playformCompress to my astro integrations, all of my svelte components break and start throwing this error
TypeError: Cannot read properties of null (reading 'nodeType') (Astro + Svelte 5)

https://stackblitz.com/edit/github-1mfzqq?file=astro.config.mjs
To reproduce run `npm i && astro build && astro preview` and check the console. You can see the desired result by running `npm i && astro dev`

**Comment by NikolaRHristov** [comment]
Setting `removeEmptyAttributes` to `false` should fix it:

```ts
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import svelte from '@astrojs/svelte';
// import compressor from 'astro-compressor';

import playformCompress from '@playform/compress';

// https://astro.build/config
export default defineConfig({
  output: 'static',
  compressHTML: true,
  integrations: [
    svelte(),
    tailwind(),
    playformCompress({
      Image: false,
      CSS: false,
      HTML: {
        'html-minifier-terser': {
          removeEmptyAttributes: false,
        },
      },
    }),
    // compressor(),
  ],
  prefetch: true,
});
```

It will be implemented as default in the latest version of `astro-compress` and `@playform/compress`.

**Comment by NikolaRHristov** [comment]
If you're using `svelte` with a `client:only` component you should be rendering it with:

```ts
<FaqQuestion faqEntry={faqEntry} client:only="svelte" />
```

See: https://docs.astro.build/en/reference/directives-reference/#clientonly

👆 This works.

That being said you should explore options in the `@playform/compress` `html-minifier-terser` where it's compatible with your `client:load` configuration.

We already found a few that are going to be implemented with the latest version but feel free to test as well.

```ts
playformCompress({
  HTML: {
    'html-minifier-terser': {
      ignoreCustomComments: [
        /^\s*#/,
        /.*\$.*/,
        /^\s*\[/,
        /^\s*\]/,
        /^\s*!/,
        /^\s*\//,

        // This was getting omitted
        /^\s*astro:end/,
      ],
    },
  },
}),
```

**Comment by NikolaRHristov** [comment]
In your case:

```ts
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import svelte from '@astrojs/svelte';
import compressor from 'astro-compressor';

import playformCompress from '@playform/compress';

// https://astro.build/config
export default defineConfig({
  output: 'static',
  compressHTML: true,
  integrations: [
    svelte(),
    tailwind(),
    playformCompress({
      Image: false,
      CSS: false,
      HTML: {
        'html-minifier-terser': {
          ignoreCustomFragments: false,
        },
      },
    }),
    compressor(),
  ],
  prefetch: true,
});
```

also helped.
