### ISSUE TITLE
Error when building: Cannot find module "./Pipe.js"

### ISSUE THREAD

**Issue by lucascompython** [nhristov/astro-compress#419]
In a new Astro project with nothing else installed but `@playform/compress`, I get the following error when running `bunx --bun astro build`: `Cannot find module "./Pipe.js" from "project_path/node_modules/@playform/compress/Target/Function/Integration.js"`

From what I've tested, it works just fine on version 0.1.1

bun version: 1.1.30
astro version: 4.15.12
@playform/compress version: 0.1.2

**Comment by NikolaRHristov** [comment]
Yeah I just saw that. For some reason the https://github.com/PlayForm/Compress/actions/runs/11226828151/job/31208021683 GitHub CI run omitted `Pipe.js` 
![image](https://github.com/user-attachments/assets/d9fe4d24-e7b5-43a8-826d-66fc6241d897)

`@playform/compress@v0.1.2`, `@playform/compress@v0.1.3` and `astro-compress@v2.3.2` have been unpublished.

**Comment by NikolaRHristov** [comment]
Should be fixed in the latest [@playform/compress@v0.1.4](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.1.4) and [astro-compress@v2.3.3](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.3.3)

**Comment by lucascompython** [comment]
I've upgraded to 0.1.4, and it works just fine!
Thank you!
